# Generated by Django 4.0.2 on 2022-08-29 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import item.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('title', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('O', 'Offer'), ('S', 'Search')], default='O', max_length=1)),
                ('category', models.CharField(choices=[('M', 'Material'), ('I', 'Immaterial')], default='M', max_length=1)),
                ('description', models.TextField()),
                ('itemID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Lage')], default='M', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('house_number', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=17, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=17, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareCircle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=140, null=True)),
                ('admin', models.ManyToManyField(related_name='sharecircle_admin_set', to=settings.AUTH_USER_MODEL)),
                ('flagged', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flagged', to='item.item')),
                ('user', models.ManyToManyField(default=uuid.uuid4, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPictures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('itemPicture', models.ImageField(max_length=800, upload_to=item.models.content_file_name, validators=[item.models.validate_image])),
                ('forItems', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='item.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sharecircle',
            field=models.ManyToManyField(to='item.ShareCircle'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
