# Generated by Django 4.0.2 on 2022-08-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_sharecircle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharecircle',
            name='flagged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flagged', to='item.item'),
        ),
    ]
