# Generated by Django 5.0.6 on 2024-07-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_alter_sharecircle_flagged"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="city",
        ),
        migrations.RemoveField(
            model_name="item",
            name="country",
        ),
        migrations.RemoveField(
            model_name="item",
            name="house_number",
        ),
        migrations.RemoveField(
            model_name="item",
            name="item_size",
        ),
        migrations.RemoveField(
            model_name="item",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="item",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="item",
            name="street",
        ),
        migrations.RemoveField(
            model_name="item",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="item",
            name="zipcode",
        ),
        migrations.AddField(
            model_name="item",
            name="reserved",
            field=models.BooleanField(default=False),
        ),
    ]
