# Generated by Django 5.0.6 on 2024-07-03 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_remove_sharecircle_flagged_item_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
