# Generated by Django 5.0.6 on 2024-07-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_item_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
    ]
