# Generated by Django 5.1 on 2024-10-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_itempictures_foritems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharecircle',
            name='admin',
        ),
        migrations.AlterField(
            model_name='sharecircle',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
