# Generated by Django 5.1 on 2024-10-03 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_sharecircle_admin_alter_sharecircle_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharecircle',
            name='admin',
            field=models.ManyToManyField(related_name='sharecircle_admin_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
