# Generated by Django 5.1 on 2024-12-31 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_sharecircle_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sharecircle',
            old_name='title',
            new_name='district',
        ),
        migrations.AddField(
            model_name='sharecircle',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.city'),
        ),
    ]
