# Generated by Django 5.1 on 2025-01-19 20:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_city_rename_title_sharecircle_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharecircle',
            name='district',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sharecircle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
