version: "3.5"

services:
  redis:
    image: redis:latest
    networks: 
      - redisnet

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - dbnet

  
  django_asgi:
    container_name: django_asgi
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 um_be.asgi:application"
    volumes:
      - .:/code
    networks: 
      - webnet
      - redisnet
      - dbnet
    links:
      - redis
  
  nginx:
    image: nginx:1.15.0
    depends_on:
      - django_asgi
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    networks:
      - webnet
    ports:
      - "80:80"

networks: 
  webnet:
  redisnet:
  dbnet:
