# Generated by Django 5.1 on 2025-01-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_item'),
        ('item', '0011_city_rename_title_sharecircle_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='item',
        ),
        migrations.AddField(
            model_name='chat',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
