# Generated by Django 4.1 on 2024-06-07 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=60,
                        null=True,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "Date_of_Birth",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("bio", models.TextField(blank=True, max_length=70, null=True)),
                ("country", models.CharField(blank=True, max_length=30, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=30, null=True)),
                ("city", models.CharField(blank=True, max_length=30, null=True)),
                ("street", models.CharField(blank=True, max_length=30, null=True)),
                ("house_number", models.IntegerField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, max_length=17, null=True)),
                ("latitude", models.FloatField(blank=True, max_length=17, null=True)),
                ("profile_picture", models.ImageField(max_length=800, upload_to="")),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_freezed", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tbl_users",
            },
        ),
    ]
