# Generated by Django 4.1 on 2024-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, max_length=800, null=True, upload_to=""
            ),
        ),
    ]
