# Generated by Django 5.0.6 on 2024-08-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0008_alter_itempictures_foritems"),
        ("user", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post_circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poster",
                to="item.sharecircle",
            ),
        ),
    ]
