# Generated by Django 5.1 on 2024-12-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
